DocWorks for shipping-rates-spi - 13 changes detected, but 1 issue detected changes: Service shipping-rates-spi operation getShippingRates has changed param items doc Service shipping-rates-spi operation getShippingRates has changed param name from shippingDestination to options Service shipping-rates-spi operation getShippingRates has changed param options type Service shipping-rates-spi operation getShippingRates has changed param options doc Service shipping-rates-spi operation getShippingRates param shippingOrigin was removed Service shipping-rates-spi operation getShippingRates param buyerDetails was removed Service shipping-rates-spi operation getShippingRates param weightUnit was removed Service shipping-rates-spi operation getShippingRates param taxIncludedInPrices was removed Service shipping-rates-spi operation getShippingRates param currency was removed Service shipping-rates-spi operation getShippingRates param instanceId was removed Service shipping-rates-spi operation getShippingRates param shippingRateDecimalPlaces was removed Service shipping-rates-spi message Cost member currency has changed doc Service shipping-rates-spi has a new message Option
issues:
ERROR: The @snippet tag - file 'velo-docs/examples/TEST.es6' not found. File: shipping-rates-spi.js line: 1