DocWorks for shipping-rates-spi - 3 changes detected, but 1 issue detected changes: Service shipping-rates-spi operation getShippingRates has changed param options type Service shipping-rates-spi message Option was removed Service shipping-rates-spi has a new message Options
issues:
ERROR: The @snippet tag - file 'velo-docs/examples/TEST.es6' not found. File: shipping-rates-spi.js line: 1